ThermoSoftware/core/views.py
from flask import request, render_template, Blueprint, redirect, url_for, flash, jsonify
from ThermoSoftware import thread
from threading import Thread
import serial
from flask_login import current_user

# Blueprint definieren
core = Blueprint('core',__name__)


# Funktion die Multi-Threading erlaubt
def start_after_app_run():
    global arduinoData
    arduinoData=serial.Serial('COM3', 115200)
    arduinoData.close()
    arduinoData.open() 
    arduinoData.timeout = 1
    
# INDEX
@core.route('/')
def index():
    # Landing Pages für verschiedene Rolen
    if current_user.is_authenticated:
        if current_user.has_role('User'):
            return redirect(url_for("users.account"))
        if current_user.has_role('Admin'):
            return redirect(url_for("users.listusers"))
        
    return redirect(url_for("users.login"))
        

# BENUTZER HILFE
@core.route('/info')
def info():
    return render_template('info.html')


# THERMOSTAT
@core.route('/thermostat', methods=['GET','POST'])
def thermostat():

    # Suche nach Arduino 
    global thread
    if thread is None:
        thread = Thread(target=start_after_app_run)
        thread.start()
    
    # Temperatur und Luftfeuchtigkeit auf None gesetzt um Fehler vorzubeugen
    temp = None
    humidity = None

    # Error Handling
    try:
        arduinoData.write(b'read_sensor_data')
        sensor_data = arduinoData.readline().decode().strip()
        try:
            temp, humidity = sensor_data.split(',')
        except ValueError:
            temp = None
            humidity = None
    except NameError:
        try:
            arduinoData.write(b'read_sensor_data')
            sensor_data = arduinoData.readline().decode().strip()
            temp, humidity = sensor_data.split(',')
        except NameError:
            pass

    return render_template('thermostat.html', temp=temp, humidity=humidity)


# HILFSROUTE FÜR TEMP/L.FEUCH. AKTUALISIERUNG
@core.route('/get_values', )
def get_values():
    arduinoData.write(b'r') # Sende Kommando zu Arduino
    sensor_data = arduinoData.readline().decode('utf-8') # Lese Daten von Arduino

    # Zerlegung der empfangenen Daten in Temperatur- und Luftfeuchtigkeitswerte
    try:
        temp, humidity = sensor_data.split(',')
        temp = float(temp)
        temp = format(temp, '.2f')
        humidity = float(humidity)
        humidity = format(humidity, '.2f')
    except ValueError:
        # Fehler beim Parsen von Daten aufgetreten dann:
        temp = None
        humidity = None

    data = {
        'temp': temp,
        'humidity': humidity
    }

    # Rückgabe des Wörterbuchs als JSON-Antwort
    return jsonify(data)


# HILFSROUTE FÜR DATEN AN ARDUINO SENDEN
@core.route('/send', methods=['POST'])
def send():
    # Ganzzahligen Wert aus Formularübermittlung abrufen
    value = int(request.form['value'])
    
    # Ganzzahligen Wert an das Arduino-Board senden
    arduinoData.write(str(value).encode())
    
    flash('Temperatur ist eingestellt', 'warning')
    return redirect(url_for("core.thermostat"))


ThermoSoftware/users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from ThermoSoftware import db
from ThermoSoftware.models import User, Role
from ThermoSoftware.users.forms import deleteRoleForm,LoginForm,UpdateUserForm,RegistrationForm,deleteUserForm 
from ThermoSoftware.users.picture_handler import add_profile_pic
from sqlalchemy.exc import IntegrityError
from flask_security import roles_required

# Blueprint definieren
users = Blueprint('users',__name__)

# Registration
@users.route('/user_register', methods=['GET', 'POST'])
@login_required
@roles_required('Admin')
def register():
    form = RegistrationForm()
    try:
        if form.validate_on_submit():
            user = User(email=form.email.data, username=form.username.data, password=form.password.data)
            role = Role.query.filter_by(id=form.role.data).first()
            user.roles.append(role)
            db.session.add(user)
            db.session.commit()
            flash('User erfolgreich registriert!', 'success')
            return redirect(url_for('users.listusers'))
    except IntegrityError:
            flash('Name oder Passwort schon vergeben!', 'danger')
            return redirect(url_for('users.register'))

    return render_template('register.html',form=form, legend="Benutzer registrieren")

# login
@users.route('/user_login',methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user is not None and user.check_password(form.password.data):

            login_user(user, form.remember_me.data)
            flash('Anmeldung erfolgreich!', 'success')

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                if User.has_role(current_user, 'Admin'):
                    next = url_for('users.listusers')
                else:
                    next = url_for('users.account') 

            return redirect(next)
        flash('Ungültiges Username oder Passwort!', "danger")

    return render_template('login.html',form=form,legend="Log in")


# logout
@users.route("/logout")
def logout():
    logout_user()
    flash('Logout erfolgreich!', 'success')
    return redirect(url_for("core.index"))


# Edit account (update UserForm)
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic
        
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form, legend="Benutzer Information")

# Users view
@users.route('/listusers')
@login_required
@roles_required('Admin')
def listusers():
    headings = ("Id", "Name", "Date", "Role", "Email", "Picture")
    userTable = [[user.id, user.username, user.date, user.which_role(), user.email, user.profile_image] for user in User.query.all()]
    return render_template('listusers.html', headings=headings, table = userTable, legend="Benutzer Liste")

# Roles view
@users.route('/listroles')
@login_required
@roles_required('Admin')
def listroles():
    headings = ("Id", "Name")
    roleTable = [[role.id, role.name] for role in Role.query.all()]
    return render_template('listroles.html', headings=headings, table = roleTable, legend="Rollen Liste")


#################################################################
# HILFS-ROUTEN

# Delete User
@users.route('/users_delete', methods=['GET', 'POST'])
@login_required
@roles_required('Admin')
def user_delete():
    form = deleteUserForm()
    form.target_username.choices=[(user.username) for user in User.query.order_by('username')]
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.target_username.data).first()
        if user.username == 'Admin':
            flash('Benützer Admin kann nicht gelöscht werden', 'danger')
        else:
            db.session.delete(user)
            db.session.commit()
            flash('User gelöscht', 'danger')
        return redirect(url_for('users.listusers'))
    return render_template('delete.html', form=form, legend="User Löschen")

# Delete Role
@users.route('/role_delete', methods=['GET', 'POST'])
@login_required
@roles_required('Admin')
def role_delete():
    form = deleteRoleForm()
    form.target_rolename.choices=[(role.name) for role in Role.query.order_by('id')]
    if form.validate_on_submit():
        role = Role.query.filter_by(name=form.target_rolename.data).first()
        if role.name == 'Admin':
            flash('Benützer Admin kann nicht gelöscht werden', 'danger')
        else:
            db.session.delete(role)
            db.session.commit()
            flash('Role gelöscht', 'danger')
        return redirect(url_for('role.listroles'))
    return render_template('delete_role.html', form=form, legend="Role Löschen")

ThermoSoftware/templates/account.html
{% extends "base.html" %}
{% block content %}

<h1>Konto Bearbeiten</h1>
<hr class="border-bottom border-info mb-4">
<br>
<div class="container">
  <form  method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <legend class="border-bottom border-info mb-4">{{legend}}</legend>
    <img align='center' src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}"> <div align='right'>
    </div>
    <hr width="640px;" color=#5bc0de>
    <div class="form-group">
      {{ form.username.label(class="form-group") }}
      {{form.username(class='form-control', readonly=true)  }}
    </div>
    <div class="form-group">
      {{ form.email.label(class="form-group") }}
      {{form.email(class='form-control', readonly=true)  }}
    </div>
    <div class="form-group">
      {{ form.picture.label(class="form-group") }}
      {{ form.picture(class="form-control-file") }}
    </div>
    <br>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info text-dark") }}
    </div>
</div>

  </form>

</div>

{% endblock content %}

ThermoSoftware/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.3.slim.js" integrity="sha256-DKU1CmJ8kBuEwumaLuh9Tl/6ZB6jzGOBV/5YpNE2BWc=" crossorigin="anonymous"></script>    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <title>Thermostat Software</title>
  </head>

  <body>
  <ul class="navbar container fixed-top navbar-light" style="background-color: #5bc0de;">
    <a href="#"><img src="{{url_for('static',filename="Icon.jpg")}}" width="70" height="45"></a>
    {% if current_user.is_authenticated %}
    <li class="nav-link"><a class="text-dark" href="{{ url_for('core.thermostat') }}">Smart Thermostat</a></li>
    {% if current_user.has_role('Admin') %}
    <li class="nav-link"><a class="text-dark" href="{{ url_for('users.listusers') }}">Dashboard</a></li>
      {% endif %}
    <li class="nav-link"><a class="text-dark" href="{{ url_for('users.account') }}">Konto bearbeiten</a></li>
    <li class="nav-link"><a class="text-dark" href="{{ url_for('core.info') }}">Hilfe</a></li>
    <li class="nav-link"><a class="text-dark" href="{{ url_for('users.logout') }}">Log Out</a></li>
    {% else %}
    <li class="nav-link"><a class="text-dark" href="{{ url_for('core.info') }}">Hilfe</a></li>
    {% endif %}
  </ul>

  <div class="container"><br><br><br><br>
    {% for categories, message in get_flashed_messages(with_categories=true) %}
    <div class="alert alert-{{ categories }}">
    <button type="button" class="close"
    data-dismiss="alert">&times;</button>
    {{ message }}
    </div>
    {% endfor %}
</body>

<br>
<div class="container">
  {% block content %}

  {% endblock %}
</div>
</html>

ThermoSoftware/templates/delete.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <form method="POST">
      {{form.hidden_tag()}}
      <legend class="border-bottom border-info mb-4">{{legend}}</legend>
      <div class="form-group">
        {{form.target_username.label(class="form-control-label")}}
        {{form.target_username(class="form-control form-control-lg")}}
      </div>
      <div class="form-group">
        {{form.submit(class="btn btn-outline-info text-dark")}}
      </div>
    </form>
  </div>

{% endblock %}

ThermoSoftware/templates/delete_role.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <form method="POST">
      {{form.hidden_tag()}}
      <legend class="border-bottom border-info mb-4">{{legend}}</legend>
      <div class="form-group">
        {{form.target_rolename.label(class="form-control-label")}}
        {{form.target_rolename(class="form-control form-control-lg")}}
      </div>
      <div class="form-group">
        {{form.submit(class="btn btn-outline-info text-dark")}}
      </div>
    </form>
  </div>

{% endblock %}

ThermoSoftware/templates/info.html
{% extends "base.html" %}
{% block content %}
<h1>Hilfe</h1>
<hr class="border-bottom border-info mb-4">
<br>
  <div class="jumbotron">
    <h1>Brauchen Sie Hilfe?</h1><br/>
    <h4>Melden Sie sich per E-Mail an: <strong>firmaCPS@smartThermostat.de</strong></h4>
    <br>
    {% if current_user.is_authenticated %}
    {% else %}
    <p>Zurück zum <a class="text-info" href="{{ url_for('users.login') }}"><strong>Login</strong></a>.</p>
    {% endif %}
  </div>
{% endblock %}

ThermoSoftware/templates/listroles.html
{% extends "base.html" %}
{% block content %}


<section class="container">
    <br>
    <legend class="border-bottom border-info mb-4">{{legend}}</legend>
    <table class="table table-striped">
        <tr style="background-color: #5bc0de">
            {% for heading in headings %}
            <th scope="col">{{ heading }}</a></th>
            {% endfor %}
        </tr>
    {% for line in table %}
        <tr>
        {% for column in line %}
            <td scope="col">{{ column }}</td>
        {% endfor %}
        </tr>
    {% endfor %}
    </table>
    </section>

    <div align='right'>
        <button type="button" class="btn btn-outline-info"><a class="text-dark" style="text-decoration: none" href="{{ url_for('users.role_delete') }}">Role löschen</a></button>
    </div>

{% endblock %}

ThermoSoftware/templates/listusers.html
{% extends "base.html" %}
{% block content %}

<h1>Dashboard</h1>
<hr class="border-bottom border-info mb-4">
<br>
<div>
    <p>Verfügbare Rollen:      <button type="button" class="btn btn-outline-info"><a class="text-dark" style="text-decoration: none" href="{{ url_for('users.listroles') }}">Rolen</a></button></p>
</div>

<section class="container">
<br>
<legend class="border-bottom border-info mb-4">{{legend}}</legend>
<table class="table table-striped">
    <tr style="background-color: #5bc0de">
        {% for heading in headings %}
        <th scope="col">{{ heading }}
        </th>
        {% endfor %}
    </tr>
{% for line in table %}
    <tr>
    {% for column in line %}
        <td scope="col">{{ column }}</td>
    {% endfor %}
    </tr>
{% endfor %}
</table>
</section>

<div align='right'>
    <button type="button" class="btn btn-outline-info"><a class="text-dark" style="text-decoration: none" href="{{ url_for('users.user_delete') }}">User löschen</a></button>
</div>
<br>
<div align='right'>
    <button type="button" class="btn btn-outline-info"><a class="text-dark" style="text-decoration: none" href="{{ url_for('users.register') }}">User hinzufügen</a></button>
</div>
<br>


{% endblock %}

ThermoSoftware/templates/login.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <form class="form-group" method="POST">
    {{form.hidden_tag()}}
    <legend class="border-bottom border-info mb-4">{{legend}}</legend>
    <div class="form-group">
      {{form.email.label(class="form-control-label")}}
      {{form.email(class="form-control form-control-lg")}}
    </div>
    <div class="form-group">
      {{form.password.label(class="form-control-label")}}
      {{form.password(class="form-control form-control-lg")}}
    </div>
    <div class="form-group form-check">
      {{form.remember_me}}
      {{form.remember_me.label(class="form-control-label")}} 
    </div>
    <div class="form-group">
      {{form.submit(class="btn btn-outline-info text-dark")}}
      <a href="#">Password vergessen?</a>
    </div>
  </form>
  <br>
  <div align='center'> <h4>All Rights Reserverd:</h4> Sara Amorosa, Milana Popović and Claudia Silva</div>
</div>
{% endblock %}

ThermoSoftware/templates/register.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <form method="POST">
    {{form.hidden_tag()}}
    <legend class="border-bottom border-info mb-4">{{legend}}</legend>
    <div class="form-group">
      {{form.email.label(class="form-control-label")}}
      {{form.email(class="form-control form-control-lg")}}
    </div>
    <div class="form-group">
      {{form.username.label(class="form-control-label")}}
      {{form.username(class="form-control form-control-lg")}}
    </div>
    <div class="form-group">
      {{form.password.label(class="form-control-label")}}
      {{form.password(class="form-control form-control-lg")}}
    </div>
    <div class="form-group">
      {{form.pass_confirm.label(class="form-control-label")}}
      {{form.pass_confirm(class="form-control form-control-lg")}}
    </div>
    <div class="form-group">
      {{form.role.label(class="form-control-label")}}
      {{form.role}}
    </div>
    <div class="form-group">
      {{form.submit(class="btn btn-outline-info text-dark")}}
    </div>
  </form>
</div>
{% endblock %}

ThermoSoftware/templates/thermostat.html
{% extends "base.html" %}
{% block content %}

<h1>Smart Thermostat</h1>
<hr class="border-bottom border-info mb-4">
<br>
<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
<div class="jumbotron jumbotron-fluid">
    <h1>Temperatur und Luftfeuchtigkeit:</h1>
    <br>
    <div align='center'>
    <p id="temp"><span id="temp">N/A</span></p>
    <p id="humidity"><span id="humidity">N/A</span></p>
</div>
</div>
      <script>
        // Function to update temperature and humidity values
        function updateValues() {
            // Make AJAX request to Flask app to get updated temperature and humidity values
            $.get('/get_values', function(data) {
                // Check if received data is valid
                if (data && data.temp != null && data.humidity != null && data.temp !== undefined && data.humidity !== undefined) {
                    // Update temperature and humidity values in the HTML elements
                    $('#temp').text('Aktuelle Temperatur: ' + data.temp + ' °C');
                    $('#humidity').text('Aktuelle Luftfeuchtigkeit: ' + data.humidity + ' %');
                } else {
                    // Handle invalid data
                    console.error('Received invalid data:', data);
                }
            }).fail(function(jqXHR, textStatus, errorThrown) {
                // Handle AJAX request failure
                console.error('AJAX request failed:', textStatus, errorThrown);
            });
        }
        setInterval(updateValues, 2000);
    </script>

<div class="jumbotron jumbotron-fluid">
    <h1>Geben Sie die gewünschte Temperatur ein:</h1>
    <br>
    <div align='center'>
    <form method="POST" action="/send">
      <input type="number" name="value" min="0" max="35"> <strong>°C</strong>
      <input type="submit" value="Bestätigen">
    </form> 
</div>
</div>  
</body>


{% endblock %}